name: Daily Fact

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  send-fact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_HISTORICAL_FACTS }}
        run: python send_fact.py

      - name: Commit updated sent facts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add sent.json
          git commit -m "Update sent facts" || echo "No changes"
          git push
